import rawProgressData from "@/data/progress-updates.json"

/** The date the project started, as a calendar date (YYYY-MM-DD) in
 * `PROJECT_TIMEZONE` — the day work began on the proposal/scope/roadmap/
 * research plan, not the first code push. Change this if the real kickoff
 * date turns out to be different — week numbers below are all calculated
 * from this one value. scripts/generate-progress-draft.mjs keeps its own
 * copy (plain Node, no bundler) — update both if this changes. */
export const PROJECT_START_DATE = "2026-08-14"

/** Documented for readers of the page; week boundaries are calculated on
 * calendar dates (YYYY-MM-DD), so this doesn't need a timezone library to
 * take effect — it just says which timezone those calendar dates are in. */
export const PROJECT_TIMEZONE = "Asia/Kolkata"

export type EvidenceLink = {
  label: string
  url: string
}

export type ProgressUpdateStatus = "draft" | "published"

export type ProgressUpdate = {
  id: string
  status: ProgressUpdateStatus
  /** Calendar week number (from PROJECT_START_DATE) this update starts in. */
  weekStart: number
  /** Calendar week number this update ends in — equal to weekStart for a
   * single-week update, higher for an update spanning several weeks. */
  weekEnd: number
  /** Reporting period: the day after the previous published update's
   * periodEnd (or PROJECT_START_DATE for the very first update), through
   * the day this update was published. This is a reporting window, not
   * time spent working. */
  periodStart: string
  periodEnd: string
  title: string
  summary: string
  /** Research, discussions, decisions, documentation, design or
   * development completed during the period — not inferred from code. */
  completed?: string[]
  added?: string[]
  improved?: string[]
  fixed?: string[]
  removed?: string[]
  /** A deliberate change of plan or direction during this period (e.g.
   * abandoning a phase of the original roadmap for a different way of
   * working). Rendered as a callout, since it's a decision, not a task. */
  approachChange?: string
  /** What was shown or tested, and with whom — only set this when that
   * actually happened and was recorded; a code push alone doesn't imply
   * testing or validation. */
  testing?: string[]
  /** What was learned from user or stakeholder feedback — same rule as
   * `testing`: only set when it was actually recorded. */
  feedback?: string[]
  unfinished?: string[]
  blockers?: string[]
  nextSteps?: string[]
  evidence?: EvidenceLink[]
  /** The last commit this update's auto-drafted sections were generated
   * from, so the next draft can resume from here instead of repeating it. */
  lastIncludedCommit?: string
  /** True while a section of this update was produced by the commit-scan
   * script and hasn't been hand-reviewed yet. */
  autoGenerated?: boolean
}

type ProgressData = {
  updates: ProgressUpdate[]
}

const data = rawProgressData as ProgressData

/** Calendar-day difference, ignoring time of day — dates are plain
 * YYYY-MM-DD strings so this doesn't drift across timezones or DST. */
function daysBetween(fromIso: string, toIso: string) {
  const from = new Date(`${fromIso}T00:00:00Z`)
  const to = new Date(`${toIso}T00:00:00Z`)
  return Math.round((to.getTime() - from.getTime()) / 86_400_000)
}

export function weekNumberForDate(dateIso: string, startIso: string = PROJECT_START_DATE) {
  const days = daysBetween(startIso, dateIso)
  return Math.max(1, Math.floor(days / 7) + 1)
}

export function weekLabel(update: Pick<ProgressUpdate, "weekStart" | "weekEnd">) {
  return update.weekStart === update.weekEnd
    ? `Week ${update.weekStart}`
    : `Weeks ${update.weekStart}–${update.weekEnd}`
}

export function formatDate(dateIso: string) {
  return new Date(`${dateIso}T00:00:00Z`).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  })
}

export function dateRangeLabel(update: Pick<ProgressUpdate, "periodStart" | "periodEnd">) {
  if (update.periodStart === update.periodEnd) return formatDate(update.periodStart)
  return `${formatDate(update.periodStart)} – ${formatDate(update.periodEnd)}`
}

export function getAllUpdates(): ProgressUpdate[] {
  return data.updates
}

/** Newest first, by the end of the reporting period. */
export function getPublishedUpdates(): ProgressUpdate[] {
  return data.updates
    .filter((update) => update.status === "published")
    .sort((a, b) => (a.periodEnd < b.periodEnd ? 1 : a.periodEnd > b.periodEnd ? -1 : 0))
}

export function getLatestUpdateDate(updates: ProgressUpdate[]): string | undefined {
  return updates[0]?.periodEnd
}
